import { NextRequest } from 'next/server';
import { prisma, createSuccessResponse, createErrorResponse } from '@/lib/api-utils';

// GET /api/scheduled-orders - List scheduled orders with filtering
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const vendorId = searchParams.get('vendorId');
    const status = searchParams.get('status');
    const startDate = searchParams.get('startDate');
    const endDate = searchParams.get('endDate');

    const where: any = {};
    if (vendorId) where.vendorId = vendorId;
    if (status) where.status = status;
    if (startDate && endDate) {
      where.scheduleDate = {
        gte: new Date(startDate),
        lte: new Date(endDate),
      };
    } else if (startDate) {
      where.scheduleDate = { gte: new Date(startDate) };
    } else if (endDate) {
      where.scheduleDate = { lte: new Date(endDate) };
    }

    const orders = await prisma.scheduledOrder.findMany({
      where,
      include: {
        vendor: {
          select: {
            id: true,
            name: true,
          },
        },
        purchaseOrder: {
          select: {
            id: true,
            orderNumber: true,
            status: true,
          },
        },
      },
      orderBy: [
        { scheduleDate: 'asc' },
        { vendor: { name: 'asc' } },
      ],
    });

    return createSuccessResponse({
      orders,
      total: orders.length,
    });
  } catch (error: any) {
    console.error('Error fetching scheduled orders:', error);
    return createErrorResponse(
      'FETCH_ERROR',
      'Failed to fetch scheduled orders',
      500
    );
  }
}

// POST /api/scheduled-orders - Create a new scheduled order
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      vendorId,
      scheduleDate,
      deliveryDate,
      status,
      autoGenerated,
      notes,
    } = body;

    if (!vendorId || !scheduleDate || !deliveryDate) {
      return createErrorResponse(
        'VALIDATION_ERROR',
        'vendorId, scheduleDate, and deliveryDate are required',
        400
      );
    }

    const order = await prisma.scheduledOrder.create({
      data: {
        vendorId,
        scheduleDate: new Date(scheduleDate),
        deliveryDate: new Date(deliveryDate),
        status: status || 'upcoming',
        autoGenerated: autoGenerated !== undefined ? autoGenerated : false,
        notes,
      },
      include: {
        vendor: {
          select: {
            id: true,
            name: true,
          },
        },
      },
    });

    return createSuccessResponse(order, 'Scheduled order created successfully', 201);
  } catch (error: any) {
    console.error('Error creating scheduled order:', error);
    return createErrorResponse(
      'CREATE_ERROR',
      `Failed to create scheduled order: ${error.message}`,
      500
    );
  }
}

export const dynamic = 'force-dynamic';
