'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { CalendarViewEnhanced } from '@/components/calendar/calendar-view-enhanced';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Calendar, Plus, RefreshCw, Settings, Trash2 } from 'lucide-react';
import Link from 'next/link';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

interface ScheduledOrder {
  id: string;
  vendorId: string;
  vendorName: string;
  status: string;
  deliveryDate: Date;
  autoGenerated: boolean;
  purchaseOrder?: {
    id: string;
    orderNumber: string;
    status: string;
  };
}

interface Vendor {
  id: string;
  name: string;
}

interface CalendarData {
  month: string;
  startDate: string;
  endDate: string;
  orders: ScheduledOrder[];
  ordersByDate: Record<string, ScheduledOrder[]>;
  vendors: Vendor[];
  summary: {
    totalOrders: number;
    upcoming: number;
    due: number;
    placed: number;
    delivered: number;
  };
}

export default function OrderCalendarPage() {
  const router = useRouter();
  const [currentMonth, setCurrentMonth] = useState<string>(() => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  });
  const [selectedVendor, setSelectedVendor] = useState<string>('all');
  const [calendarData, setCalendarData] = useState<CalendarData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);

  // Fetch calendar data
  const fetchCalendarData = async () => {
    setIsLoading(true);
    try {
      const params = new URLSearchParams({ month: currentMonth });
      if (selectedVendor !== 'all') {
        params.append('vendorId', selectedVendor);
      }

      const response = await fetch(`/api/calendar/orders?${params}`);
      if (!response.ok) {
        throw new Error('Failed to fetch calendar data');
      }

      const result = await response.json();
      if (result.success) {
        setCalendarData(result.data);
      } else {
        console.error('Failed to fetch calendar data:', result.error);
      }
    } catch (error) {
      console.error('Error fetching calendar data:', error);
    } finally {
      setIsLoading(false);
    }
  };

  // Generate scheduled orders
  const handleGenerateOrders = async () => {
    setIsGenerating(true);
    try {
      const response = await fetch('/api/scheduled-orders/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ daysAhead: 90 }), // Generate 3 months ahead
      });

      if (!response.ok) {
        throw new Error('Failed to generate orders');
      }

      const result = await response.json();
      if (result.success) {
        alert(`Generated ${result.data.summary.created} scheduled orders`);
        fetchCalendarData(); // Refresh calendar
      } else {
        alert(`Error: ${result.error.message}`);
      }
    } catch (error) {
      console.error('Error generating orders:', error);
      alert('Failed to generate scheduled orders');
    } finally {
      setIsGenerating(false);
    }
  };

  // Clear and regenerate scheduled orders
  const handleClearAndRegenerate = async () => {
    if (!confirm('This will clear all auto-generated orders (that don\'t have purchase orders attached) and regenerate from current vendor schedules. Continue?')) {
      return;
    }
    
    setIsGenerating(true);
    try {
      // First, clear existing auto-generated orders
      const clearResponse = await fetch('/api/scheduled-orders', {
        method: 'DELETE',
      });

      if (!clearResponse.ok) {
        throw new Error('Failed to clear orders');
      }

      const clearResult = await clearResponse.json();
      
      // Then generate new ones
      const generateResponse = await fetch('/api/scheduled-orders/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ daysAhead: 90 }),
      });

      if (!generateResponse.ok) {
        throw new Error('Failed to generate orders');
      }

      const generateResult = await generateResponse.json();
      if (generateResult.success) {
        alert(`Cleared ${clearResult.data.deleted} old orders, generated ${generateResult.data.summary.created} new orders from current schedules`);
        fetchCalendarData();
      } else {
        alert(`Error: ${generateResult.error.message}`);
      }
    } catch (error) {
      console.error('Error clearing and regenerating orders:', error);
      alert('Failed to clear and regenerate scheduled orders');
    } finally {
      setIsGenerating(false);
    }
  };

  // Handle order click
  const handleOrderClick = (order: ScheduledOrder) => {
    if (order.purchaseOrder) {
      // Navigate to existing purchase order
      router.push(`/ordering/purchase-orders/${order.purchaseOrder.id}`);
    } else {
      // Navigate to 6-week analysis page with vendor pre-selected
      router.push(`/orders?vendorId=${order.vendorId}`);
    }
  };

  // Effect to fetch data when month or vendor changes
  useEffect(() => {
    fetchCalendarData();
  }, [currentMonth, selectedVendor]);

  if (isLoading && !calendarData) {
    return (
      <div className="container mx-auto py-8 px-4">
        <div className="flex items-center justify-center h-64">
          <div className="text-center">
            <RefreshCw className="h-8 w-8 animate-spin mx-auto mb-2 text-purple-600" />
            <p className="text-gray-600">Loading calendar...</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto py-8 px-4">
      {/* Page header */}
      <div className="mb-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center space-x-3">
            <Calendar className="h-8 w-8 text-purple-600" />
            <h1 className="text-3xl font-bold text-gray-900">Order Calendar</h1>
          </div>
          <div className="flex items-center space-x-2">
            <Link href="/ordering/vendor-schedules">
              <Button variant="outline">
                <Settings className="h-4 w-4 mr-2" />
                Vendor Schedules
              </Button>
            </Link>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  disabled={isGenerating}
                  className="bg-purple-600 hover:bg-purple-700"
                >
                  {isGenerating ? (
                    <>
                      <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                      Working...
                    </>
                  ) : (
                    <>
                      <Plus className="h-4 w-4 mr-2" />
                      Generate Orders
                    </>
                  )}
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem onClick={handleGenerateOrders}>
                  <Plus className="h-4 w-4 mr-2" />
                  Add New Orders
                </DropdownMenuItem>
                <DropdownMenuItem onClick={handleClearAndRegenerate} className="text-orange-600">
                  <Trash2 className="h-4 w-4 mr-2" />
                  Clear & Regenerate All
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>

        {/* Filters */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Filters</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <Label htmlFor="vendor-filter">Vendor</Label>
                <Select
                  value={selectedVendor}
                  onValueChange={setSelectedVendor}
                >
                  <SelectTrigger id="vendor-filter">
                    <SelectValue placeholder="All Vendors" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Vendors</SelectItem>
                    {calendarData?.vendors.map((vendor) => (
                      <SelectItem key={vendor.id} value={vendor.id}>
                        {vendor.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Calendar view */}
      {calendarData && (
        <CalendarViewEnhanced
          month={currentMonth}
          orders={calendarData.orders}
          ordersByDate={calendarData.ordersByDate}
          summary={calendarData.summary}
          vendors={calendarData.vendors}
          onMonthChange={setCurrentMonth}
          onOrderClick={handleOrderClick}
          onRefresh={fetchCalendarData}
        />
      )}
    </div>
  );
}
