'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { CalendarViewEnhanced } from '@/components/calendar/calendar-view-enhanced';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Calendar, Plus, RefreshCw, Settings, RotateCcw, CalendarDays, CalendarRange, ChevronLeft, ChevronRight } from 'lucide-react';
import Link from 'next/link';

interface ScheduledOrder {
  id: string;
  vendorId: string;
  vendorName: string;
  status: string;
  deliveryDate: Date;
  orderDeadline?: string;
  autoGenerated: boolean;
  purchaseOrder?: {
    id: string;
    orderNumber: string;
    status: string;
  };
}

interface Vendor {
  id: string;
  name: string;
}

interface CalendarData {
  month: string;
  startDate: string;
  endDate: string;
  orders: ScheduledOrder[];
  ordersByDate: Record<string, ScheduledOrder[]>;
  vendors: Vendor[];
  summary: {
    totalOrders: number;
    upcoming: number;
    due: number;
    placed: number;
    delivered: number;
  };
}

const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

function getWeekDates(baseDate: Date): Date[] {
  const dates: Date[] = [];
  const startOfWeek = new Date(baseDate);
  startOfWeek.setDate(baseDate.getDate() - baseDate.getDay()); // Start from Sunday
  
  for (let i = 0; i < 7; i++) {
    const date = new Date(startOfWeek);
    date.setDate(startOfWeek.getDate() + i);
    dates.push(date);
  }
  return dates;
}

function formatDate(date: Date): string {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
}

function WeeklyView({ 
  weekDates, 
  ordersByDate, 
  onOrderClick,
  onWeekChange 
}: { 
  weekDates: Date[];
  ordersByDate: Record<string, ScheduledOrder[]>;
  onOrderClick: (order: ScheduledOrder) => void;
  onWeekChange: (delta: number) => void;
}) {
  const today = formatDate(new Date());
  
  return (
    <Card>
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg flex items-center gap-2">
            <CalendarRange className="h-5 w-5" />
            Week of {weekDates[0].toLocaleDateString('en-AU', { month: 'short', day: 'numeric' })} - {weekDates[6].toLocaleDateString('en-AU', { month: 'short', day: 'numeric', year: 'numeric' })}
          </CardTitle>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={() => onWeekChange(-1)}>
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <Button variant="outline" size="sm" onClick={() => onWeekChange(0)}>
              Today
            </Button>
            <Button variant="outline" size="sm" onClick={() => onWeekChange(1)}>
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-7 gap-2">
          {weekDates.map((date, idx) => {
            const dateKey = formatDate(date);
            const orders = ordersByDate[dateKey] || [];
            const isToday = dateKey === today;
            const isPast = dateKey < today;
            
            return (
              <div 
                key={dateKey}
                className={`border rounded-lg p-2 min-h-[120px] ${
                  isToday ? 'bg-purple-50 border-purple-300' : 
                  isPast ? 'bg-gray-50' : 'bg-white'
                }`}
              >
                <div className={`text-sm font-medium mb-2 ${isToday ? 'text-purple-700' : 'text-gray-600'}`}>
                  <div>{DAY_NAMES[idx]}</div>
                  <div className="text-lg font-bold">{date.getDate()}</div>
                </div>
                <div className="space-y-1">
                  {orders.length === 0 ? (
                    <p className="text-xs text-gray-400 italic">No orders</p>
                  ) : (
                    orders.map((order) => (
                      <div
                        key={order.id}
                        onClick={() => onOrderClick(order)}
                        className={`text-xs p-1.5 rounded cursor-pointer truncate ${
                          order.status === 'placed' ? 'bg-green-100 text-green-800' :
                          order.status === 'due' ? 'bg-orange-100 text-orange-800' :
                          order.status === 'delivered' ? 'bg-blue-100 text-blue-800' :
                          'bg-gray-100 text-gray-800'
                        } hover:opacity-80`}
                        title={`${order.vendorName}${order.orderDeadline ? ` - ${order.orderDeadline}` : ''}`}
                      >
                        {order.vendorName}
                        {order.orderDeadline && (
                          <span className="ml-1 opacity-75">({order.orderDeadline})</span>
                        )}
                      </div>
                    ))
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </CardContent>
    </Card>
  );
}

export default function OrderCalendarPage() {
  const router = useRouter();
  const [viewMode, setViewMode] = useState<'month' | 'week'>('week');
  const [currentMonth, setCurrentMonth] = useState<string>(() => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  });
  const [weekBaseDate, setWeekBaseDate] = useState<Date>(new Date());
  const [selectedVendor, setSelectedVendor] = useState<string>('all');
  const [calendarData, setCalendarData] = useState<CalendarData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);

  // Fetch calendar data
  const fetchCalendarData = async () => {
    setIsLoading(true);
    try {
      const params = new URLSearchParams({ month: currentMonth });
      if (selectedVendor !== 'all') {
        params.append('vendorId', selectedVendor);
      }

      const response = await fetch(`/api/calendar/orders?${params}`);
      if (!response.ok) {
        throw new Error('Failed to fetch calendar data');
      }

      const result = await response.json();
      if (result.success) {
        setCalendarData(result.data);
      } else {
        console.error('Failed to fetch calendar data:', result.error);
      }
    } catch (error) {
      console.error('Error fetching calendar data:', error);
    } finally {
      setIsLoading(false);
    }
  };

  // Generate scheduled orders
  const handleGenerateOrders = async () => {
    setIsGenerating(true);
    try {
      const response = await fetch('/api/scheduled-orders/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ daysAhead: 90 }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate orders');
      }

      const result = await response.json();
      if (result.success) {
        alert(`Generated ${result.data.summary.created} scheduled orders`);
        fetchCalendarData();
      } else {
        alert(`Error: ${result.error.message}`);
      }
    } catch (error) {
      console.error('Error generating orders:', error);
      alert('Failed to generate scheduled orders');
    } finally {
      setIsGenerating(false);
    }
  };

  // Clear and regenerate scheduled orders
  const handleClearAndRegenerate = async () => {
    if (!confirm('This will clear all auto-generated orders (that don\'t have purchase orders attached) and regenerate from current vendor schedules. Continue?')) {
      return;
    }
    
    setIsGenerating(true);
    try {
      const clearResponse = await fetch('/api/scheduled-orders', {
        method: 'DELETE',
      });

      if (!clearResponse.ok) {
        throw new Error('Failed to clear orders');
      }

      const clearResult = await clearResponse.json();
      
      const generateResponse = await fetch('/api/scheduled-orders/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ daysAhead: 90 }),
      });

      if (!generateResponse.ok) {
        throw new Error('Failed to generate orders');
      }

      const generateResult = await generateResponse.json();
      if (generateResult.success) {
        alert(`Cleared ${clearResult.data.deleted} old orders, generated ${generateResult.data.summary.created} new orders from current schedules`);
        fetchCalendarData();
      } else {
        alert(`Error: ${generateResult.error.message}`);
      }
    } catch (error) {
      console.error('Error clearing and regenerating orders:', error);
      alert('Failed to clear and regenerate scheduled orders');
    } finally {
      setIsGenerating(false);
    }
  };

  // Handle order click
  const handleOrderClick = (order: ScheduledOrder) => {
    if (order.purchaseOrder) {
      router.push(`/ordering/purchase-orders/${order.purchaseOrder.id}`);
    } else {
      router.push(`/orders?vendorId=${order.vendorId}`);
    }
  };

  // Handle week navigation
  const handleWeekChange = (delta: number) => {
    if (delta === 0) {
      setWeekBaseDate(new Date());
    } else {
      const newDate = new Date(weekBaseDate);
      newDate.setDate(newDate.getDate() + (delta * 7));
      setWeekBaseDate(newDate);
    }
  };

  // Effect to fetch data when month or vendor changes
  useEffect(() => {
    fetchCalendarData();
  }, [currentMonth, selectedVendor]);

  // Sync month view with week view
  useEffect(() => {
    const weekMonth = `${weekBaseDate.getFullYear()}-${String(weekBaseDate.getMonth() + 1).padStart(2, '0')}`;
    if (weekMonth !== currentMonth) {
      setCurrentMonth(weekMonth);
    }
  }, [weekBaseDate]);

  const weekDates = getWeekDates(weekBaseDate);

  if (isLoading && !calendarData) {
    return (
      <div className="container mx-auto py-8 px-4">
        <div className="flex items-center justify-center h-64">
          <div className="text-center">
            <RefreshCw className="h-8 w-8 animate-spin mx-auto mb-2 text-purple-600" />
            <p className="text-gray-600">Loading calendar...</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto py-8 px-4">
      {/* Page header */}
      <div className="mb-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center space-x-3">
            <Calendar className="h-8 w-8 text-purple-600" />
            <h1 className="text-3xl font-bold text-gray-900">Order Calendar</h1>
          </div>
          <div className="flex items-center space-x-2">
            {/* View Toggle */}
            <div className="flex bg-gray-100 rounded-lg p-1 mr-2">
              <Button
                variant={viewMode === 'week' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setViewMode('week')}
                className={viewMode === 'week' ? 'bg-purple-600 hover:bg-purple-700' : ''}
              >
                <CalendarRange className="h-4 w-4 mr-1" />
                Week
              </Button>
              <Button
                variant={viewMode === 'month' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setViewMode('month')}
                className={viewMode === 'month' ? 'bg-purple-600 hover:bg-purple-700' : ''}
              >
                <CalendarDays className="h-4 w-4 mr-1" />
                Month
              </Button>
            </div>
            
            <Link href="/ordering/vendor-schedules">
              <Button variant="outline">
                <Settings className="h-4 w-4 mr-2" />
                Vendor Schedules
              </Button>
            </Link>
            <Button
              variant="outline"
              onClick={handleClearAndRegenerate}
              disabled={isGenerating}
              className="text-orange-600 border-orange-300 hover:bg-orange-50"
            >
              <RotateCcw className="h-4 w-4 mr-2" />
              Rebuild
            </Button>
            <Button
              onClick={handleGenerateOrders}
              disabled={isGenerating}
              className="bg-purple-600 hover:bg-purple-700"
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                  Working...
                </>
              ) : (
                <>
                  <Plus className="h-4 w-4 mr-2" />
                  Generate
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Filters */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Filters</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <Label htmlFor="vendor-filter">Vendor</Label>
                <Select
                  value={selectedVendor}
                  onValueChange={setSelectedVendor}
                >
                  <SelectTrigger id="vendor-filter">
                    <SelectValue placeholder="All Vendors" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Vendors</SelectItem>
                    {calendarData?.vendors.map((vendor) => (
                      <SelectItem key={vendor.id} value={vendor.id}>
                        {vendor.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Calendar views */}
      {calendarData && (
        <>
          {viewMode === 'week' ? (
            <WeeklyView 
              weekDates={weekDates}
              ordersByDate={calendarData.ordersByDate}
              onOrderClick={handleOrderClick}
              onWeekChange={handleWeekChange}
            />
          ) : (
            <CalendarViewEnhanced
              month={currentMonth}
              orders={calendarData.orders}
              ordersByDate={calendarData.ordersByDate}
              summary={calendarData.summary}
              vendors={calendarData.vendors}
              onMonthChange={setCurrentMonth}
              onOrderClick={handleOrderClick}
              onRefresh={fetchCalendarData}
            />
          )}
        </>
      )}
    </div>
  );
}
