const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function cleanup() {
  // Delete all scheduled orders with 2026 dates
  const result = await prisma.scheduledOrder.deleteMany({
    where: {
      scheduleDate: {
        gte: new Date('2026-01-01'),
        lte: new Date('2026-12-31')
      },
      autoGenerated: true
    }
  });
  
  console.log(`Deleted ${result.count} scheduled orders with 2026 dates`);
  
  await prisma.$disconnect();
}

cleanup().catch(console.error);
