'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ChevronLeft, ChevronRight, Calendar as CalendarIcon } from 'lucide-react';

interface ScheduledOrder {
  id: string;
  vendorId: string;
  vendorName: string;
  status: string;
  deliveryDate: Date;
  autoGenerated: boolean;
  purchaseOrder?: {
    id: string;
    orderNumber: string;
    status: string;
  };
}

interface CalendarViewProps {
  month: string; // Format: YYYY-MM
  orders: ScheduledOrder[];
  ordersByDate: Record<string, ScheduledOrder[]>;
  summary: {
    totalOrders: number;
    upcoming: number;
    due: number;
    placed: number;
    delivered: number;
  };
  onMonthChange: (month: string) => void;
  onOrderClick: (order: ScheduledOrder) => void;
}

export function CalendarView({
  month,
  orders,
  ordersByDate,
  summary,
  onMonthChange,
  onOrderClick,
}: CalendarViewProps) {
  const [year, monthNum] = month.split('-').map(Number);

  // Get first day of month and total days
  const firstDay = new Date(year, monthNum - 1, 1);
  const lastDay = new Date(year, monthNum, 0);
  const daysInMonth = lastDay.getDate();
  const startDayOfWeek = firstDay.getDay(); // 0 = Sunday

  // Generate calendar grid
  const calendarDays: (number | null)[] = [];

  // Add empty cells for days before month starts
  for (let i = 0; i < startDayOfWeek; i++) {
    calendarDays.push(null);
  }

  // Add days of month
  for (let day = 1; day <= daysInMonth; day++) {
    calendarDays.push(day);
  }

  // Navigation handlers
  const handlePreviousMonth = () => {
    const prevMonth = new Date(year, monthNum - 2, 1);
    const newMonth = `${prevMonth.getFullYear()}-${String(prevMonth.getMonth() + 1).padStart(2, '0')}`;
    onMonthChange(newMonth);
  };

  const handleNextMonth = () => {
    const nextMonth = new Date(year, monthNum, 1);
    const newMonth = `${nextMonth.getFullYear()}-${String(nextMonth.getMonth() + 1).padStart(2, '0')}`;
    onMonthChange(newMonth);
  };

  const handleToday = () => {
    const today = new Date();
    const newMonth = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}`;
    onMonthChange(newMonth);
  };

  // Get orders for a specific date
  const getOrdersForDate = (day: number): ScheduledOrder[] => {
    const dateKey = `${year}-${String(monthNum).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    return ordersByDate[dateKey] || [];
  };

  // Status colors
  const getStatusColor = (status: string): string => {
    switch (status) {
      case 'upcoming':
        return 'bg-blue-100 text-blue-800 border-blue-300';
      case 'due':
        return 'bg-yellow-100 text-yellow-800 border-yellow-300';
      case 'placed':
        return 'bg-green-100 text-green-800 border-green-300';
      case 'delivered':
        return 'bg-gray-100 text-gray-800 border-gray-300';
      default:
        return 'bg-gray-100 text-gray-800 border-gray-300';
    }
  };

  const monthName = new Date(year, monthNum - 1).toLocaleString('default', { month: 'long' });

  return (
    <div className="space-y-4">
      {/* Header with navigation */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <CalendarIcon className="h-6 w-6 text-purple-600" />
              <CardTitle className="text-2xl">
                {monthName} {year}
              </CardTitle>
            </div>
            <div className="flex items-center space-x-2">
              <Button
                variant="outline"
                size="sm"
                onClick={handleToday}
              >
                Today
              </Button>
              <Button
                variant="outline"
                size="icon"
                onClick={handlePreviousMonth}
              >
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <Button
                variant="outline"
                size="icon"
                onClick={handleNextMonth}
              >
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {/* Summary statistics */}
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
            <div className="text-center p-3 bg-gray-50 rounded-lg border border-gray-200">
              <div className="text-2xl font-bold text-gray-900">{summary.totalOrders}</div>
              <div className="text-xs text-gray-600">Total Orders</div>
            </div>
            <div className="text-center p-3 bg-blue-50 rounded-lg border border-blue-200">
              <div className="text-2xl font-bold text-blue-900">{summary.upcoming}</div>
              <div className="text-xs text-blue-600">Upcoming</div>
            </div>
            <div className="text-center p-3 bg-yellow-50 rounded-lg border border-yellow-200">
              <div className="text-2xl font-bold text-yellow-900">{summary.due}</div>
              <div className="text-xs text-yellow-600">Due</div>
            </div>
            <div className="text-center p-3 bg-green-50 rounded-lg border border-green-200">
              <div className="text-2xl font-bold text-green-900">{summary.placed}</div>
              <div className="text-xs text-green-600">Placed</div>
            </div>
            <div className="text-center p-3 bg-gray-50 rounded-lg border border-gray-200">
              <div className="text-2xl font-bold text-gray-900">{summary.delivered}</div>
              <div className="text-xs text-gray-600">Delivered</div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Calendar grid */}
      <Card>
        <CardContent className="p-4">
          {/* Day headers */}
          <div className="grid grid-cols-7 gap-2 mb-2">
            {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day) => (
              <div
                key={day}
                className="text-center font-semibold text-gray-700 py-2 text-sm"
              >
                {day}
              </div>
            ))}
          </div>

          {/* Calendar days */}
          <div className="grid grid-cols-7 gap-2">
            {calendarDays.map((day, index) => {
              if (day === null) {
                return <div key={`empty-${index}`} className="min-h-[120px] bg-gray-50 rounded" />;
              }

              const dayOrders = getOrdersForDate(day);
              const isToday =
                new Date().getDate() === day &&
                new Date().getMonth() === monthNum - 1 &&
                new Date().getFullYear() === year;

              return (
                <div
                  key={day}
                  className={`min-h-[120px] border rounded-lg p-2 ${
                    isToday ? 'border-purple-500 bg-purple-50' : 'border-gray-200 bg-white'
                  }`}
                >
                  <div className={`text-sm font-semibold mb-2 ${
                    isToday ? 'text-purple-700' : 'text-gray-700'
                  }`}>
                    {day}
                  </div>

                  {/* Orders for this day */}
                  <div className="space-y-1">
                    {dayOrders.map((order) => (
                      <button
                        key={order.id}
                        onClick={() => onOrderClick(order)}
                        className={`w-full text-left px-2 py-1 rounded text-xs border transition-all hover:shadow-md ${getStatusColor(
                          order.status
                        )}`}
                      >
                        <div className="font-medium truncate">{order.vendorName}</div>
                        {order.purchaseOrder && (
                          <div className="text-[10px] opacity-75">
                            {order.purchaseOrder.orderNumber}
                          </div>
                        )}
                      </button>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {/* Legend */}
      <Card>
        <CardContent className="p-4">
          <div className="flex flex-wrap gap-4 text-sm">
            <div className="flex items-center space-x-2">
              <div className="w-4 h-4 bg-blue-100 border border-blue-300 rounded"></div>
              <span>Upcoming</span>
            </div>
            <div className="flex items-center space-x-2">
              <div className="w-4 h-4 bg-yellow-100 border border-yellow-300 rounded"></div>
              <span>Due</span>
            </div>
            <div className="flex items-center space-x-2">
              <div className="w-4 h-4 bg-green-100 border border-green-300 rounded"></div>
              <span>Placed</span>
            </div>
            <div className="flex items-center space-x-2">
              <div className="w-4 h-4 bg-gray-100 border border-gray-300 rounded"></div>
              <span>Delivered</span>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
